static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  virtual_hosts:
                    - name: local_route
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: local_server
                http_filters:
                  - name: envoy.filters.http.httpwasm
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.http_wasm.v3.GuestConfig
                      name: "httpwasm-coraza-waf"
                      max_request_bytes: 5242880
                      configuration:
                        "@type": "type.googleapis.com/google.protobuf.StringValue"
                        value: |
                          {
                            "directives": [
                              "Include @recommended-conf",
                              "Include @crs-setup-conf",
                              "SecDefaultAction \"phase:3,log,auditlog,pass\"",
                              "SecDefaultAction \"phase:4,log,auditlog,pass\"",
                              "SecDefaultAction \"phase:5,log,auditlog,pass\"",
                              "SecRuleEngine On",
                              "SecResponseBodyMimeType text/plain text/html text/xml application/json",
                              "SecDebugLogLevel 9",
                              "#Include @owasp_crs/*.conf",
                              "SecRule REQUEST_URI \"@streq /admin\" \"id:101,phase:1,t:lowercase,deny\" \nSecRule REQUEST_BODY \"@rx maliciouspayload\" \"id:102,phase:2,t:lowercase,deny\" \nSecRule RESPONSE_HEADERS::status \"@rx 406\" \"id:103,phase:3,t:lowercase,deny\" \nSecRule RESPONSE_BODY \"@contains responsebodycode\" \"id:104,phase:4,t:lowercase,deny\""
                            ]
                          }
                      code:
                        local:
                          filename: "/build/coraza-http-wasm.wasm"
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: local_server
      connect_timeout: 6000s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: local_server
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: httpbin
                      port_value: 8000

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 6081
